### PR TITLE
Include compute/types.hpp into compute/core.hpp

### PR DESCRIPTION
**Pull request by ddemidov**

### CODE REVIEW

**Comment by ddemidov** [comment]
https://travis-ci.org/ddemidov/compute/builds/293076294

**Comment by ddemidov** [comment]
I have no idea what happens with OSX (linux failures are due to `-Werror` and are not caused by this PR). But I was able to reproduce the problem with 8f77efd0ef1aeeeed09fd097a675daa4eb9da644 locally, and cee5bd0fbb163565cacae2738b543a9c8e905543 fixes it for me.

**Comment by henryiii** [comment]
I still have a feeling that there's a different meaning for `long` (32 vs. 64 bits) somewhere. `long long` is always 64, and `int` should be 32.

I'll merge it and see what happens. I was unable to get it to work when I first started this PR, but probably tried a different location.

**Comment by ddemidov** [comment]
Yes, `long` is 4 bytes on Windows, but it should not be a problem there. The problem with OSX is that `std::is_same<unsigned long, size_t>` and `std::is_same<long, ptrdiff_t>` (assuming 64bit system) are false. OSX is unique in making a distinction between integer types of the same size.

**Pull request merged**
